medicalstore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('medicine.urls')),
    path('medicineapi/', include('medicineapi.urls')),
    

]

medicine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('' ,views.signup_page,name = 'register'),
    path('login/',views.login_page,name ='log'),
    path('create/',views.create ,name = 'create'),
    path('data/',views.data ,name = 'data'),
    path('update/<int:id>/',views.update ,name = 'update'),
    path('delete/<int:pk>/',views.delete ,name = 'delete'),
    path('search/',views.search_view ,name ='search'),
    path('logout/', views.logout_view, name='logout'),
]

medicine/models.py
from django.db import models

# Create your models here.





class Medicine(models.Model):
    name = models.CharField(max_length=500)
    catagory = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)


# models.py

medicine/forms.py
from django import forms
from .models import Medicine


class Medicinedata(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = (('name', 'catagory','price'))

medicine/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login , logout
from .models import Medicine
from .forms import  Medicinedata
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required


# views.py


# def register(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             # login(request, user)
#             # messages.success(request, 'You have successfully signed up.')
#             # return redirect('home')  # Replace 'home' with the name of your homepage URL
#             return render(request ,'login.html')
#     else:
#         form = UserCreationForm()
#     return render(request, 'register.html', {'form': form})


from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect
 
def signup_page(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()  # Save the new user
            # Redirect to login page after successful signup
            return redirect('log')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render,redirect
from django.contrib.auth import login 
from django.views.decorators.cache import cache_control

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Authenticate the user
            user = form.get_user()
            login(request, user)
            # Redirect to home page after successful login
            return redirect('data')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})
    # response = render(request, 'login.html', {'form': form})
    # response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    # response['Pragma'] = 'no-cache'
    # response['Expires'] = '0'
    # return response
    



# def login_view(request):
#     if request.user.is_authenticated:
#         return render(request, 'data.html')
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         print(user)
#         if user is not None:
#             login(request, user)
#             # return redirect ('data')
#             return render(request, 'data.html')

            
#         else:
#             msg = 'Error Login'
#             form = AuthenticationForm(request.POST)
#             return render(request, 'login.html', {'form': form, 'msg': msg})
#     else:
#         form = AuthenticationForm()
#         return render(request, 'login.html', {'form': form})
    
# def login_page(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             return redirect('data')
#         else:
#             form = AuthenticationForm()
#             return render(request, 'login.html', {'form': form})
 

@login_required(login_url='/register/')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def data(request):
    medicine_list=Medicine.objects.all()
    return render(request,'data.html',{'medicine_list':medicine_list})

@login_required(login_url='/register/')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def  create(request):
    if request.method == 'POST':
        form =Medicinedata(request.POST)
        if form.is_valid():
            form.save()
            return redirect('data')
    else:
        form =Medicinedata()
    return render(request, 'create.html', {'form': form})


# def data(request):
#     medicine_list=Medicine.objects.all()
#     return render(request,'data.html',{'medicine_list':medicine_list})


# def update(request, id):
#     product = Medicine.objects.get(pk=id)
#     if request.method == 'POST':
#         form = Medicinedata(request.POST,instance=product)
#         if form.is_valid():
#             form.save()
#             return redirect('data')
#     else:
#         form =Medicinedata(instance=product)           
#     return render(request, 'edit.html', {'form': form})

from django.shortcuts import render, redirect
from .models import Medicine
from .forms import Medicinedata


@login_required(login_url='/register/')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update(request, id):
    product = Medicine.objects.get(pk=id)
    if request.method == 'POST':
        form = Medicinedata(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('data')
    else:
        form = Medicinedata(instance=product)           
    return render(request, 'edit.html', {'form': form, 'product': product})



#delete 
@login_required(login_url='/register/')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete(request,pk):
    medicine_list =Medicine.objects.get(pk=pk)  
    if request.method == 'POST':
        medicine_list.delete()
        return redirect('data')
    return render(request,'data.html',{'medicine_list': medicine_list})


# logout

# def logout(request):
#     return render(request,'entry.html')

def logout_view(request):
    logout(request)
    return redirect('register')


@login_required(login_url='/register/')
def search_view(request):
    if 'q' in request.GET:
        q = request.GET['q']
        # Construct a query to search for 'name' containing the search query
        search_query = Q(name__istartswith=q)
        
        # Filter Medicine objects based on the search query
        medicine_list = Medicine.objects.filter(search_query)
        context = {
            'medicine_list': medicine_list,
            'query': q,
        }
        return render(request, 'search_results.html', context)
    else:
        # If no search query provided, return an empty search page or handle it accordingly
        return render(request, 'data.html' )

medicine/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Libre+Franklin:wght@300;400&family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Sometype+Mono:wght@700&family=Young+Serif&display=swap" rel="stylesheet">
   
    <title>Medical Store</title>
    <style>
   
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg  bg-dark">

    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark "> -->
        <div class="container-fluid">
          <!-- <a class="navbar-brand color-white" href="#">MEDSTORE</a> -->
          <a class="navbar-brand" href="#" style="color: white;">MEDSTORE</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <!-- <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
            </ul> -->
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
            <li class="nav-item me-2">
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="logout " style="border: none; background-color: transparent;color: white;">Logout</button>
            </form>
            {% endif %}
            
              <!-- <li class="nav-item me-2">
               <a class="nav-link" class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                 <a class="nav-link" href="#">Sign Up</a> -->
              </li>
             
            </ul>
          </div>
        </div>
      </nav>
      {% block 'content' %}
      
    {% endblock %}

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

medicine/templates/create.html
{%extends 'base.html'%}
{% load static %}
{%block 'content' %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title justify-content-center">Add Medicine</h5>
          <form method="POST" action="{% url 'create' %}">
            {% csrf_token %}
            <div class="mb-3">
              <label for="exampleInputName" class="form-label">Medicine Name</label>
              <input type="text" class="form" name="name" id="exampleInputName" placeholder=" Medicine name">
            </div>
            <div class="mb-3">
              <label for="exampleInputcatagory1" class="form-label">Medicine catagory</label>
              <input type="text" class="form" name="catagory" id="exampleInputcatagory1" aria-describedby="medHelp" placeholder="Medicine catagory">
            </div>
            <div class="mb-3">
              <label for="exampleInputprice1" class="form-label">Medicine Price</label>
              <input type="text" class="form" name="price" id="exampleInputprice" aria-describedby="priceHelp" placeholder="Enter price">
            </div>
            <button type="submit" class="btn btn-primary">Submit </button>
          </form>
          
        </div>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" type="text/css" href="{% static 'static/create.css' %}">

{% endblock%}

medicine/templates/data.html
{%extends 'base.html'%}
{% load static %}
{%block 'content' %}

<!-- <div class="container">
    <div class="row mb-3">
        <!-- Left-aligned column for search form -->
        <!-- <div class="col">
            <form class="d-flex mt-3" role="search" method="get" action="{% url 'search' %}">
            
                <input class="form me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-warning ms-0 ml-0" type="submit">Search</button>
            </form>
        </div>
      
        <div class="col-auto mt-3">
            <a href="{% url 'create' %}" class="btn btn-primary">Add Medicine</a>
        </div>
    </div>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Medicine ID</th>
                <th>Medicine Name</th>
                <th>Medicine Category</th>
                <th>Medicine Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for medicine in medicine_list %}
            <tr>
                <td>{{ medicine.id }}</td>
                <td>{{ medicine.name }}</td>
                <td>{{ medicine.catagory }}</td> 
                <td>{{ medicine.price }}</td>
                <td>
                    <a href="{% url 'update' medicine.id %}" class="btn btn-success" role="button">Edit</a>
                    <a href="{% url 'delete' medicine.id %}" class="btn btn-danger" role="button">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody> -->
    <!-- </table>
</div> -->

{% block content %}

<div class="container">
    <div class="row mb-3">
        <!-- Left-aligned column for search form -->
        <div class="col">
            <form class="d-flex mt-3" role="search" method="get" action="{% url 'search' %}">
            
                <input class="form me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-warning ms-0 ml-0" type="submit">Search</button>
            </form>
        </div>
        <!-- Right-aligned column for Add button -->
        <div class="col-auto mt-3">
            <a href="{% url 'create' %}" class="btn btn-primary">Add Medicine</a>
        </div>
    </div>

    <!-- Medicine Table -->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Medicine ID</th>
                <th>Medicine Name</th>
                <th>Medicine Category</th>
                <th>Medicine Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for medicine in medicine_list %}
            <tr>
                <td>{{ medicine.id }}</td>
                <td>{{ medicine.name }}</td>
                <td>{{ medicine.catagory }}</td> 
                <td>{{ medicine.price }}</td>
                <td>
                    <a href="{% url 'update' medicine.id %}" class="btn btn-success" role="button">Edit</a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ medicine.id }}">
                        Delete
                    </button>
                </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal{{ medicine.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ medicine.id }}" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel{{ medicine.id }}">Confirm Delete</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete "{{ medicine.name }}"?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button> 
                            <!-- <a href="{% url 'delete' medicine.id %}" class="btn btn-danger">Delete</a>  -->
                        
                        <form method="post" action="{% url 'delete' medicine.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'static/data.css' %}">

 

{%endblock%}

medicine/templates/delete.html
{% extends 'base.html'%}
{% load static %}

{%block 'content' %}

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Delete Medicine</h5>
            <form method="post" action="">
                {% csrf_token %}
                <p>Are you sure you want to delete ?</p>
                <div class="row">
                    <div class="col">
                        <input type="submit" value="Confirm" class="btn btn-danger btn-block">
                    </div>
                    <div class="col-auto">
                        <a class="btn btn-primary btn-block me-2" href="{% url 'data' %}" role="button">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<link rel="stylesheet" type="text/css" href="{% static 'static/delete.css' %}">
{% endblock %}

medicine/templates/edit.html
{%extends 'base.html'%}
{% load static %}
{%block 'content' %}

 <div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title justify-content-center">Edit Medicine</h5>
          <form method="POST" action="">
            {% csrf_token %}
            <div class="mb-3"> 
              <label for="exampleInputName" class="form-label">Medicine Name</label> 
              <!-- <input type="text" class="form" name="name" id="exampleInputName" placeholder=" Medicine name">  -->
              <input type="text" id="id_name" class="form" name="name" placeholder=" Medicine name" value="{{ form.name.value }}">
            </div>
            <div class="mb-3">
              <label for="exampleInputcatagory1" class="form-label">Medicine catagory</label> 
              <!-- <input type="text" class="form" name="catagory" id="exampleInputcatagory1" aria-describedby="medHelp" placeholder="Medicine catagory">  -->
              <input type="text" id="id_catagory" class="form" placeholder=" Medicine name" name="catagory" value="{{ form.catagory.value }}"> 

              
            </div>
            <div class="mb-3">
              <label for="exampleInputprice1" class="form-label">Medicine Price</label> 
              <!-- <input type="text" class="form" name="price" id="exampleInputprice" aria-describedby="priceHelp" placeholder="Enter price"> -->
              <input type="text"  class="form"  id="id_price" name="price" placeholder="Enter price" value="{{ form.price.value }}">
            </div>
            <button type="submit" class="btn btn-warning">Submit </button>
          </form>
          
        </div>
      </div>
    </div>
  </div>
</div>


<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"> -->
    <!-- <title>Edit Medicine</title> -->
    <!-- Include Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body> -->
    <!-- <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Edit Medicine</h1>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            
                            <div class="form-group">
                                <label for="id_name">Name:</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            
                            <div class="form-group">
                                <label for="id_catagory">Category:</label>
                                {{ form.catagory }}
                                {{ form.catagory.errors }}
                            </div>
                            
                            <div class="form-group">
                                <label for="id_price">Price:</label>
                                {{ form.price }}
                                {{ form.price.errors }}
                            </div>
                            
                            <!-- Add more fields here as needed -->
<!--                             
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
<!-- 
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Edit Medicine</title>
        <!-- Include Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
    <body>  -->
        <!-- <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title">Edit Medicine</h1>
                            <form method="post">
                                {% csrf_token %}
                                <!-- {{ form.non_field_errors }} -->
<!--                                 
                                <div class="form-group row">
                                    <label for="id_name" class="col-sm-3 col-form-label">Name:</label>
                                    <div class="col-sm-9">
                                        <input type="text" id="id_name" name="name" class="form-control" value="{{ form.name.value }}"> -->
                                        <!-- {{ form.name.errors }} -->
                                    <!-- </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label for="id_catagory" class="col-sm-3 col-form-label">Category:</label>
                                    <div class="col-sm-9">
                                        <input type="text" id="id_category" name="catagory" class="form-control" value="{{ form.catagory.value }}"> -->
                                        <!-- {{ form.catagory.errors }} -->
                                    <!-- </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label for="id_price" class="col-sm-3 col-form-label">Price:</label>
                                    <div class="col-sm-9"> -->
                                        <!-- {{ form.price }} -->
                                        <!-- <input type="text" id="id_price" name="price" class="form-control" value="{{ form.price.value }}"> -->
                                        <!-- {{ form.price.errors }} -->
                                    <!-- </div>
                                </div>
                                 -->
                                <!-- Add more fields here as needed -->
                                
                                <!-- <div class="form-group row">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
    
    


<link rel="stylesheet" type="text/css" href="{% static 'static/create.css' %}">

{% endblock%}

medicine/templates/entry.html
{% extends 'base.html'%}
{% load static %}
{% block 'content' %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title justify-content-center" id="sign">Sign Up</h5>
          <form>
            <div class="mb-2 ">
              <label for="exampleInputName" class="form-label">Name</label>
              <input type="text" class="form" id="exampleInputName" placeholder="Enter your name">
            </div>
            <div class="mb-2">
              <label for="exampleInputEmail1" class="form-label">Email</label>
              <input type="email" class="form" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your email">
            </div>
            <div class="mb-2">
              <label for="exampleInputEmail1" class="form-label">password</label>
              <input type="password" class="form" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your email">
            </div>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">confirm password</label>
              <input type="password" class="form" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="confirm your email">
            </div>
            
            <a class="btn btn-primary" href="#" role="button">Sign up</a>
          </form>
          <p class="mt-3 ">Already have an account? <a href="#" id="link">Log in</a></p>
        </div>
      </div>
    </div>
  </div>
</div>


  
<link rel="stylesheet" type="text/css" href="{% static 'static/signup.css' %}">

{% endblock%}

medicine/templates/home.html
<!-- {% extends 'base.html'%}
{% block 'content' %}

<span>
    <a href="{%url 'sign' %}" class="btn btn-primary" value="edit" type="submit">Signup</a>
    <a href="{%url 'login'  %}" class="btn btn-danger" value="edit" type="submit">Login</a>
</span>
<form action="" method="POST">
    {{form.errors}}
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputName" class="form-label">Name</label>
      <input type="text" class="form" id="exampleInputName" name="name" aria-describedby="emailHelp">
    </div>
      
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email </label>
        <input type="email" class="form" name="email" id="exampleInputEmail1" aria-describedby="emailHelp">
        <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
      <!-- </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form" name="password" id="exampleInputPassword1">
      </div>
      <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
          <input type="password" class="form" name="confirmpassword" id="exampleInputPassword1">
      </div>
      <button type="submit" class="btn btn-primary">Sign in</button>
    </form>

  
{% endblock %}  -->


<h1>Edit Medicine</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        
        <label for="id_name">Name:</label>
        {{ form.name }}
        {{ form.name.errors }}
        
        <label for="id_catagory">Manufacturer:</label>
        {{ form.catagory }}
        {{ form.catagoryr.errors }}
        <label for="id_catagory">Manufacturer:</label>
        {{ form.price }}
        {{ form.price.errors }}
        
        <!-- Add more fields here as needed -->
        
        <button type="submit">Update</button>
    </form>
</body>
</html>

medicine/templates/login.html
{%extends 'base.html'%}
{% load static %}
{%block 'content' %}



<!-- <div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title justify-content-center">login</h5>
          <form action="{% url 'log' %}" method="POST">
            <div class="mb-3">
              <label for="exampleInputName" class="form-label">Name</label>
              <input type="text" class="form" id="exampleInputName" placeholder="Enter your name">
            </div>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">password</label>
              <input type="password" class="form" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your password">
            </div>
         <button type="submit" class="btn btn-primary">Login</button> -->
            <!-- <a class="btn btn-primary" href="{% url 'data' %}" role="button">Login</a>
          </form> -->
          <!-- <p class="mt-3">Already have an account? <a href="#">Log in</a></p> -->
        <!-- </div>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" type="text/css" href="{% static 'static/login.css' %}"> -->

   
    <!-- <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form> -->
    <div class="container d-flex justify-content-center align-items-center vh-100">
      <div class="card mt-5">
          <div class="card-body">
              <h5 class="card-title custom-title">Login</h5>
              <form method="POST" novalidate>
                  {% csrf_token %}
                  
                  <!-- Username Field -->
                  <div class="form-group mb-3">
                      <label for="id_username">Username:</label>
                      <input type="text" id="id_username" name="username" class="form-control" required>
                      {% if form.errors.username %}
                      <small class="text-danger">{{ form.errors.username }}</small>
                  {% endif %}
                  </div>
                  
                  <!-- Password Field -->
                  <div class="form-group mb-3">
                      <label for="id_password">Password:</label>
                      <input type="password" id="id_password" name="password" class="form-control" required>
                      {% if form.errors.password %}
                        <small class="text-danger">{{ form.errors.password }}</small>
                    {% endif %}
                  </div>
                  
                  <button type="submit" class="btn btn-primary">Login</button>
              </form>
          </div>
      </div>
  </div>
  <link rel="stylesheet" type="text/css" href="{% static 'static/login.css' %}">

{% endblock%}